import importlib
import datetime

from astral import LocationInfo

import astronomy
import gui

importlib.reload(astronomy)
importlib.reload(gui)

DEFAULT_TIMESTEP = 3  # minutes #TODO: Move this to constants


def stargazing_calendar():

    # Should create a GUI where you select a location as defined in
    # locations.py
    gui.create_stargazing_gui()

    # You select location, adjust settings, hit run: calendar is created
    # year_info should be saved to data. If there is already year_info of equal
    # or higher temporal resolution, just use that (may need to be evenly
    # divisible for better plotting and such).

    # Calendar should be saved as an image in the calendars folder
    # Can extend the plot_day to make prettier plots, and then plot_month.
    # Calendar could have two forms, one is normal, the other is 1080p image
    # with 12 rows (months) and every day plotted.

    # Click on a day (or mouse-over?) to see a plot of it; which should be
    # generated by plot_day() or something similar. Must be quick.

    # TODO: make a gitignore; it should

    return False


def plot_day(
    location: LocationInfo,
    day: datetime.date,
    timestep_minutes: int = DEFAULT_TIMESTEP,
):

    day_info = astronomy.get_day_info(
        location=location,
        day=day,
        timestep_minutes=timestep_minutes,
    )

    gui.plot_day(day_info)


def get_year_info(
    location: LocationInfo,
    year: int,
    timestep_minutes: int = DEFAULT_TIMESTEP,
):

    # Check if data already exists

    start_day = datetime.date(year, 1, 1)
    end_day = datetime.date(year, 12, 31)

    day = start_day - datetime.timedelta(days=1)
    year_info = {}
    while day < end_day:
        day = day + datetime.timedelta(days=1)
        print(day)
        year_info.update(
            {
                day: astronomy.get_day_info(
                    location=location,
                    day=day,
                    timestep_minutes=timestep_minutes,
                )
            }
        )

    return year_info
